### ISSUE TITLE
barryvdh/laravel-ide-helper 版本升级，把Barryvdh\LaravelIdeHelper\ClassMapGenerator删除了

### ISSUE THREAD

**Issue by hanyoujun** [krissss/webman-eloquent-ide-helper#1]
运行命令提示 Fatal error: Uncaught Error: Class "Barryvdh\LaravelIdeHelper\ClassMapGenerator" not found in  \vendor\kriss\webman-eloquent-ide-helper\src\Command\IdeHelperModelsCommand.php:59

建议限制版本到 [2.12.3](https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.12.3)

**Comment by krissss** [comment]
已更新，使用 `composer require kriss/webman-eloquent-ide-helper -w` 更新一下依赖
