### ISSUE TITLE
Call to undefined method Illuminate\Container\Container::runningUnitTests()

### ISSUE THREAD

**Issue by leekung** [krissss/webman-eloquent-ide-helper#2]
Start from illuminate/console 10.17.0 it requires new package "laravel/prompts"
when run `ide-helper:models` it throw error

`
PHP Fatal error:  Uncaught Error: Call to undefined method Illuminate\Container\Container::runningUnitTests() in vendor/illuminate/console/Concerns/ConfiguresPrompts.php:27
Stack trace:
#0 vendor/illuminate/console/Command.php(177): Illuminate\Console\Command->configurePrompts(Object(Symfony\Component\Console\Input\ArgvInput))
#1 vendor/symfony/console/Application.php(1063): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Kriss\WebmanEloquentIdeHelper\Command\IdeHelperModelsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 webman(45): Symfony\Component\Console\Application->run()
#5 {main}
  thrown in vendor/illuminate/console/Concerns/ConfiguresPrompts.php on line 27
`

I think it may not this package problem but just post here to let other people know

My work around is adding this line  to composer.json, run composer update

`"illuminate/console": "10.16.0"`

then run `./webman ide-helper:models` then remove that line

**Comment by krissss** [comment]
same as https://github.com/webman-tech/laravel-console/issues/2

**Comment by krissss** [comment]
update to v1.1.1
