### ISSUE TITLE
执行php webman ide-helper:models后会报如下错误

### ISSUE THREAD

**Issue by DaybreakY** [krissss/webman-eloquent-ide-helper#4]
执行php webman ide-helper:models命令后报了如下错误
其中webman/console安装的版本是1.2.39
workerman/webman-framework是1.5.11
PHP Fatal error:  Uncaught Error: Cannot use object of type Kriss\WebmanEloquentIdeHelper\Wrapper\LaravelContainerWrapper as array in /work/api/webman/vendor/barryv
dh/laravel-ide-helper/src/Console/ModelsCommand.php:142
Stack trace:
#0 /work/api/webman/vendor/illuminate/container/BoundMethod.php(36): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->handle()
#1 /work/api/webman/vendor/illuminate/container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#2 /work/api/webman/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#3 /work/api/webman/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#4 /work/api/webman/vendor/illuminate/container/Container.php(662): Illuminate\Container\BoundMethod::call()
#5 /work/api/webman/vendor/kriss/webman-eloquent-ide-helper/src/Wrapper/LaravelContainerWrapper.php(23): Illuminate\Container\Container->call()
#6 /work/api/webman/vendor/kriss/webman-eloquent-ide-helper/src/Wrapper/LaravelContainerWrapper.php(175): Kriss\WebmanEloquentIdeHelper\Wrapper\LaravelContainerWrap
per->__call()
#7 /work/api/webman/vendor/illuminate/console/Command.php(211): Kriss\WebmanEloquentIdeHelper\Wrapper\LaravelContainerWrapper->call()
#8 /work/api/webman/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#9 /work/api/webman/vendor/illuminate/console/Command.php(181): Symfony\Component\Console\Command\Command->run()
#10 /work/api/webman/vendor/symfony/console/Application.php(1063): Illuminate\Console\Command->run()
#11 /work/api/webman/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#12 /work/api/webman/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#13 /work/api/webman/webman(45): Symfony\Component\Console\Application->run()
#14 {main}
  thrown in /work/api/webman/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php on line 142

**Comment by krissss** [comment]
fixed in v1.1.2

**Comment by DaybreakY** [comment]
> v1.1.2 中修复

嗯，更新后正常了
