### ISSUE TITLE
请支持下 barryvdh/laravel-ide-helper 3.0

### ISSUE THREAD

**Issue by adacnvwp** [krissss/webman-eloquent-ide-helper#6]
你好，请支持一下barryvdh/laravel-ide-helper 3.0版本吧，不然的话，其他依赖不好升级了

**Comment by krissss** [comment]
更新下 1.2.0 ，加了支持，但是没有全面测试过，粗看了一下 v3 的 CHANGELOG，应该可以用，有问题再返回

**Comment by adacnvwp** [comment]
好的
