### ISSUE TITLE
IDE生成注释与webman模型注释分不清

### ISSUE THREAD

**Issue by youziyouzishu** [krissss/webman-eloquent-ide-helper#7]
![image](https://github.com/krissss/webman-eloquent-ide-helper/assets/48539892/c47de15c-a8c4-46e3-b428-18a3fbf38d53)
![image](https://github.com/krissss/webman-eloquent-ide-helper/assets/48539892/60ca3ab0-7a9d-487f-a6c5-13e31be0307c)

**Comment by krissss** [comment]
使用生成到模型上的方式：

`php webman ide-helper:models --write`

或者生成时提示是否要写到模型上，输入 y

**Comment by youziyouzishu** [comment]
> 使用生成到模型上的方式：
> 
> `php webman ide-helper:models --write`
> 
> 或者生成时提示是否要写到模型上，输入 y
![image](https://github.com/krissss/webman-eloquent-ide-helper/assets/48539892/212032d8-9189-4fb0-ac4b-a2bdc87e8bca)
![image](https://github.com/krissss/webman-eloquent-ide-helper/assets/48539892/0e0563f3-f822-421f-a93e-5ac93b7ce734)
直接取不出模型字段了

**Comment by youziyouzishu** [comment]
可能跟webman框架有关系 
加上声明就可以了
![image](https://github.com/krissss/webman-eloquent-ide-helper/assets/48539892/6b306f82-d789-40e8-b7c6-4a3ab0351f52)

**Comment by krissss** [comment]
使用 `Users::query()->where()->first()` 的形式代替直接使用 `Users::where`，因为 `Users::where` 的代码提示是由 webman `support\Model` 提供的，`ide-helper:models` 会给当前的 Users 模型添加 `query()` 的注释，能正常自动解析到当前的类

你加注释当然可以，但这就相当于不要用这个 ide-helper 去生成任何的提示了，用当前这个工具的目的就是为了免去一个个去写注释呀

**Comment by zhuochengs** [comment]
@YouZiXiL 您好：
想咨询下您，
https://github.com/yansongda/pay/issues/837
这个错误你最后是如何解决的？我现在也遇到了同样的问题，谢谢！
我的邮箱是624753698@qq.com,非常感谢！！

**Comment by youziyouzishu** [comment]
> @YouZiXiL 您好： 想咨询下您， [yansongda/pay#837](https://github.com/yansongda/pay/issues/837) 这个错误你最后是如何解决的？我现在也遇到了同样的问题，谢谢！ 我的邮箱是[624753698@qq.com](mailto:624753698@qq.com),非常感谢！！

应该是API密钥错了
